language: ruby
rvm:
  - "2.1.2"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.example config/database.yml
  - rake db:schema:load

script: 'CODECLIMATE_REPO_TOKEN=61a60a7d49d896226c4aac453d26b2860ddfc73a290e6ae45be69769c3712aa6 bundle exec rake'
